remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Nouman Amir
description: Compiler Engineer
github:
  is_project_page: false

baseurl: "/nouman-amir"
url: "https://NoumanAmir657.github.io"
